//
// Generated by JTB 1.3.2
//

package foo.parser.syntaxtree;

import foo.parser.syntaxtree.Node;
import foo.parser.syntaxtree.NodeToken;

/**
 * Grammar production:
 * f0 -> <IDENTIFIER>
 * f1 -> <COLON>
 * f2 -> <NUMBER>
 */
public class LabelDecl implements Node {
   public foo.parser.syntaxtree.NodeToken f0;
   public foo.parser.syntaxtree.NodeToken f1;
   public foo.parser.syntaxtree.NodeToken f2;

   public LabelDecl(foo.parser.syntaxtree.NodeToken n0, foo.parser.syntaxtree.NodeToken n1, foo.parser.syntaxtree.NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public LabelDecl(foo.parser.syntaxtree.NodeToken n0, foo.parser.syntaxtree.NodeToken n1) {
      f0 = n0;
      f1 = new NodeToken(":");
      f2 = n1;
   }

   public void accept(foo.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(foo.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(foo.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(foo.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

