//
// Generated by JTB 1.3.2
//

package foo.parser.syntaxtree;

import foo.parser.syntaxtree.Node;

/**
 * Represents a grammar choice, e.g. ( A | B )
 */
public class NodeChoice implements foo.parser.syntaxtree.Node {
   public NodeChoice(foo.parser.syntaxtree.Node node) {
      this(node, -1);
   }

   public NodeChoice(foo.parser.syntaxtree.Node node, int whichChoice) {
      choice = node;
      which = whichChoice;
   }

   public void accept(foo.parser.visitor.Visitor v) {
      choice.accept(v);
   }
   public <R,A> R accept(foo.parser.visitor.GJVisitor<R,A> v, A argu) {
      return choice.accept(v,argu);
   }
   public <R> R accept(foo.parser.visitor.GJNoArguVisitor<R> v) {
      return choice.accept(v);
   }
   public <A> void accept(foo.parser.visitor.GJVoidVisitor<A> v, A argu) {
      choice.accept(v,argu);
   }

   public Node choice;
   public int which;
}

