//
// Generated by JTB 1.3.2
//

package foo.parser.syntaxtree;

import foo.parser.syntaxtree.Node;

/**
 * The interface which NodeList, NodeListOptional, and NodeSequence
 * implement.
 */
public interface NodeListInterface extends foo.parser.syntaxtree.Node {
   public void addNode(foo.parser.syntaxtree.Node n);
   public foo.parser.syntaxtree.Node elementAt(int i);
   public java.util.Enumeration<Node> elements();
   public int size();

   public void accept(foo.parser.visitor.Visitor v);
   public <R,A> R accept(foo.parser.visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(foo.parser.visitor.GJNoArguVisitor<R> v);
   public <A> void accept(foo.parser.visitor.GJVoidVisitor<A> v, A argu);
}

