//
// Generated by JTB 1.3.2
//

package foo.parser.syntaxtree;

import foo.parser.syntaxtree.Automaton;
import foo.parser.syntaxtree.FinalStates;
import foo.parser.syntaxtree.Node;
import foo.parser.syntaxtree.NodeToken;
import foo.parser.syntaxtree.OpsDecls;
import foo.parser.syntaxtree.States;
import foo.parser.syntaxtree.TimbukTransitions;

/**
 * Grammar production:
 * f0 -> OpsDecls()
 * f1 -> Automaton()
 * f2 -> States()
 * f3 -> FinalStates()
 * f4 -> TimbukTransitions()
 * f5 -> <EOF>
 */
public class TimbukFTA implements Node {
   public foo.parser.syntaxtree.OpsDecls f0;
   public foo.parser.syntaxtree.Automaton f1;
   public foo.parser.syntaxtree.States f2;
   public foo.parser.syntaxtree.FinalStates f3;
   public foo.parser.syntaxtree.TimbukTransitions f4;
   public foo.parser.syntaxtree.NodeToken f5;

   public TimbukFTA(foo.parser.syntaxtree.OpsDecls n0, foo.parser.syntaxtree.Automaton n1, foo.parser.syntaxtree.States n2, foo.parser.syntaxtree.FinalStates n3, foo.parser.syntaxtree.TimbukTransitions n4, foo.parser.syntaxtree.NodeToken n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public TimbukFTA(OpsDecls n0, Automaton n1, States n2, FinalStates n3, TimbukTransitions n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = new NodeToken("");
   }

   public void accept(foo.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(foo.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(foo.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(foo.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

