//
// Generated by JTB 1.3.2
//

package foo.parser.syntaxtree;

import foo.parser.syntaxtree.Node;
import foo.parser.syntaxtree.NodeToken;
import foo.parser.syntaxtree.TimbukTransitionList;

/**
 * Grammar production:
 * f0 -> <TRANSITIONS>
 * f1 -> TimbukTransitionList()
 */
public class TimbukTransitions implements Node {
   public foo.parser.syntaxtree.NodeToken f0;
   public foo.parser.syntaxtree.TimbukTransitionList f1;

   public TimbukTransitions(foo.parser.syntaxtree.NodeToken n0, foo.parser.syntaxtree.TimbukTransitionList n1) {
      f0 = n0;
      f1 = n1;
   }

   public TimbukTransitions(TimbukTransitionList n0) {
      f0 = new NodeToken("Transitions");
      f1 = n0;
   }

   public void accept(foo.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(foo.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(foo.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(foo.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

